#!/usr/bin/bash
# Maintainer  : Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=void-installer
pkgdesc="Instalador oficial do Void Linux da comunidade Brasil"
pkgver=$(date +%Y%m%d)
pkgrel=$(date +%H%M)
arch=('any')
license=('MIT')
url="https://github.com/voidlinuxbr/$pkgname"
provides=("$pkgname")
source=("git+${url}.git")
md5sums=('SKIP')
depends=("bash>=0")

package() {
	local dirs=("usr" "etc" "opt")
	#   echo "DESTDIR=$DESTDIR"
	#   echo "pkgdir=$pkgdir"
	#   echo "srcdir=$srcdir"
	#   echo "_pkgsrc=$_pkgsrc"

	cd ${srcdir}/${pkgname}
	for dir in "${dirs[@]}"; do
		if [ -d "${_pkgsrc}/${dir}" ]; then
			cp -a "${_pkgsrc}/${dir}" "$DESTDIR/"
		fi
	done

   # Install binary
   install -Dm755 void-install "${pkgdir}/usr/bin/"
   install -Dm755 void-clonedisk "${pkgdir}/usr/bin/"
   install -Dm755 void-services "${pkgdir}/usr/bin/"
   install -Dm755 void-dialog-theme-selector "${pkgdir}/usr/bin/"

   # Install license file if present
   if [ -f "LICENSE" ]; then
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
   fi


}
